version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: frontend
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=prod
  
  proxy:
    build:
      context: ./proxy
